const fs = require('fs');
const path = require('path');

const root = path.resolve('/Users/claude_file/Desktop/Program/1.morphcast_test/SEEG/0719/CISCNThesis');
const figures = [
  'seeg_data_preprocessing_nature',
  'seeg_qst_dpgnet_architecture_nature',
  'seeg_onset_localization_nature',
  'seeg_top10_channel_explanation_nature',
  'seeg_inference_deployment_nature',
  'seeg_lightweight_optimization_nature'
];

const map = [
  ['SEEG data audit and patient-level sample construction', 'SEEG 数据审计与患者级样本构建'],
  ['quality control · leakage prevention · label alignment', '质量控制 · 泄漏排查 · 标签对齐'],
  ['A  SIGNAL AUDIT', 'A  信号审计'],
  ['B  QUALITY-AWARE PREPROCESSING', 'B  质量感知预处理'],
  ['C  PATIENT-LEVEL SAMPLE CONSTRUCTION', 'C  患者级样本构建'],
  ['Raw SEEG record', '原始 SEEG 记录'],
  ['channel ID · sampling rate · C x T waveform', '通道 ID · 采样率 · C x T 波形'],
  ['valid channels', '有效通道'],
  ['Audit fields', '审计字段'],
  ['shape and dtype', '张量形状与数据类型'],
  ['sampling rate and units', '采样率与单位'],
  ['missing values', '缺失值'],
  ['Leakage checks', '泄漏排查'],
  ['file and waveform hashes', '文件与波形哈希'],
  ['near-duplicate clusters', '近重复片段聚类'],
  ['metadata probe', '元数据对照模型'],
  ['freeze audit protocol before training', '训练前冻结审计规则'],
  ['Resampling and filters', '重采样与滤波'],
  ['anti-aliasing', '抗混叠'],
  ['band-pass + notch', '带通 + 陷波'],
  ['causal delay calibration', '因果延迟校准'],
  ['Bad-channel QC', '坏道质量控制'],
  ['flatline and saturation', '平线与饱和'],
  ['line-noise ratio', '工频噪声比'],
  ['artifact risk score', '伪迹风险评分'],
  ['Reference and robust scaling', '参考重构与稳健标准化'],
  ['common-average / bipolar reference', '共同平均 / 双极参考'],
  ['median-MAD normalization with clipping', 'Median-MAD 标准化与截断'],
  ['bad channels kept as an explicit mask', '坏道保留为显式掩码'],
  ['Output tensors', '输出张量'],
  ['X: B x C x T    |    channel mask M    |    frame mask', 'X: B x C x T  |  通道掩码 M  |  帧掩码'],
  ['Patient-level split', '患者级划分'],
  ['patient identity is isolated across train / validation / test', '训练、验证、测试集按患者身份隔离'],
  ['train', '训练'],
  ['validation', '验证'],
  ['test', '测试'],
  ['no random windows across the same continuous record', '同一连续记录不跨集合随机切窗'],
  ['Overlapping windows and labels', '重叠滑窗与标签'],
  ['4 s window · 0.5 s step · 0.125 s frame output', '4 s 窗口 · 0.5 s 步长 · 0.125 s 帧输出'],
  ['frame labels remain available around state transitions', '状态转变附近保留帧级标签'],
  ['Cross-subject augmentation', '跨受试者数据增强'],
  ['channel dropout · time / frequency masking · baseline drift', '通道丢弃 · 时域 / 频域掩蔽 · 基线漂移'],
  ['onset labels are transformed synchronously', 'onset 标签同步变换'],

  ['QST-DPGNet: state transition and dynamic propagation network', 'QST-DPGNet：状态转变与动态传播网络'],
  ['shared representation · multi-task heads · interpretable outputs', '共享表征 · 多任务输出头 · 可解释结果'],
  ['A  INPUT AND MASKS', 'A  输入与掩码'],
  ['B  MULTI-SCALE REPRESENTATION', 'B  多尺度表征'],
  ['C  DYNAMIC PROPAGATION', 'C  动态传播'],
  ['D  JOINT OUTPUT HEADS', 'D  联合输出头'],
  ['Window X', '窗口 X'],
  ['multichannel time series', '多通道时间序列'],
  ['optional: coordinates +', '可选：坐标 +'],
  ['brain-region soft map', '脑区软映射'],
  ['Shared temporal encoder', '共享时域编码器'],
  ['depthwise 1D convolutions', '深度可分离一维卷积'],
  ['short / mid / long receptive fields', '短 / 中 / 长感受野'],
  ['shared weights across channel IDs', '跨通道 ID 共享权重'],
  ['Time-frequency branch', '时频分支'],
  ['STFT or differentiable filter bank', 'STFT 或可微滤波器组'],
  ['log-power bands aligned to frame rate', '对数功率频带对齐帧率'],
  ['Gated fusion', '门控融合'],
  ['retains waveform and rhythm evidence', '保留波形与节律证据'],
  ['Dynamic dual graph', '解剖-功能动态图'],
  ['A_t = anatomy prior + functional dynamics', 'A_t = 解剖先验 + 功能动态'],
  ['baseline change: Delta A_t = A_t - A_baseline', '相对基线变化：Delta A_t = A_t - A_baseline'],
  ['top-k valid neighbours + node residual', '保留 top-k 有效邻居 + 节点残差'],
  ['Long-range model', '长程时序模型'],
  ['dilated depthwise TCN', '扩张深度可分离 TCN'],
  ['light gated attention', '轻量门控注意力'],
  ['Fragment state head', '片段状态头'],
  ['p_clip + calibrated probability', 'p_clip + 校准概率'],
  ['quality-weighted pooling', '质量加权池化'],
  ['Frame state + onset', '帧级状态 + onset'],
  ['p_state,t and p_onset,t', 'p_state,t 与 p_onset,t'],
  ['transition consistency', '状态转移一致性'],
  ['Channel recruitment head', '通道募集头'],
  ['r_c,t retains channel x time', 'r_c,t 保留通道 x 时间'],
  ['early recruitment + propagation', '早期募集 + 传播'],
  ['State-transition constraint', '状态转移约束'],
  ['p_onset rise -> persistent p_state', 'p_onset 上升 -> p_state 持续'],
  ['suppresses isolated spikes', '抑制孤立尖波'],
  ['Submission outputs', '提交输出'],
  ['label + p + onset time', '标签 + 概率 + onset 时间'],
  ['Top-10 official channel IDs', 'Top-10 官方通道 ID'],
  ['One shared representation jointly answers when the state changes, which channels are recruited first and how activity propagates.', '共享表征同时回答状态何时转变、哪些通道最先募集以及活动如何传播。'],

  ['Onset localization from state persistence and boundary evidence', '基于状态持续性与边界证据的 onset 定位'],
  ['window fusion · hysteresis · change-point correction', '滑窗融合 · 滞回判定 · 变化点校正'],
  ['A  WINDOW FUSION', 'A  滑窗融合'],
  ['B  JOINT STATE MACHINE', 'B  联合状态机'],
  ['C  ROBUST ONSET DECISION', 'C  稳健 onset 判定'],
  ['Overlapping windows', '重叠滑窗'],
  ['Hann-weighted frame fusion', 'Hann 加权帧融合'],
  ['Fused sequences', '融合后的序列'],
  ['state p_t', '状态 p_t'],
  ['boundary b_t', '边界 b_t'],
  ['recruitment max_c r_c,t', '募集 max_c r_c,t'],
  ['filter delay and frame-center offsets are calibrated before search', '搜索前统一校准滤波延迟与帧中心偏移'],
  ['State probabilities', '状态概率'],
  ['same time axis, different evidence roles', '同一时间轴上的不同证据'],
  ['candidate', '候选点'],
  ['window end', '窗口末端'],
  ['Joint boundary score', '联合边界评分'],
  ['earliest candidate satisfying future persistence', '满足后续持续性的最早候选点'],
  ['state rise + boundary peak + early recruitment - artifact risk', '状态上升 + 边界峰值 + 早期募集 - 伪迹风险'],
  ['the first valid peak is selected, not the first p_t > 0.5', '选择第一个满足约束的有效峰值，而非首次 p_t > 0.5'],
  ['Left-censored', '左删失'],
  ['high probability at first frame', '首帧已处于高概率状态'],
  ['onset = 0; internal flag retained', 'onset = 0；保留内部标记'],
  ['Artifact rejection', '伪迹排除'],
  ['isolated burst or flatline', '孤立爆发或平线'],
  ['cannot trigger without persistence', '缺少持续性时不能触发'],
  ['Calibrated onset time', '校准后的 onset 时间'],
  ['report precision separately from actual temporal resolution', '输出精度与实际时间分辨率分别报告'],
  ['trigger at tau_h  |  maintain at tau_l  |  tau_h > tau_l', 'tau_h 触发  |  tau_l 保持  |  tau_h > tau_l'],
  ['continuous positive duration D_min suppresses isolated spikes', '连续阳性时长 D_min 抑制孤立尖波'],
  ['State persistence, boundary evidence and change-point support are combined; no single threshold defines onset.', '联合状态持续性、边界证据与变化点支持，不由单一阈值决定 onset。'],

  ['Onset-aware Top-10 channel ranking and conditional spatial mapping', 'onset 感知的 Top-10 通道排序与条件性空间映射'],
  ['early recruitment · propagation order · coordinate-aware reporting', '早期募集 · 传播顺序 · 坐标条件化报告'],
  ['A  ONSET-AWARE EVIDENCE WINDOW', 'A  onset 感知证据窗口'],
  ['B  FUSED CHANNEL SCORE', 'B  通道融合评分'],
  ['C  RANKING AND SPATIAL CONDITION', 'C  排序与空间条件'],
  ['Channel x time recruitment', '通道 x 时间募集'],
  ['early window limits late propagation bias', '早期窗口降低晚期传播偏差'],
  ['onset', 'onset'],
  ['late propagation', '晚期传播'],
  ['internal layers', '内部层级'],
  ['onset candidate | early propagation | late propagation', 'onset 候选 | 早期传播 | 晚期传播'],
  ['first sustained recruitment', '首次持续募集'],
  ['early network propagation', '早期网络传播'],
  ['late broad synchronization', '晚期广泛同步'],
  ['S_c = weighted evidence - artifact risk', 'S_c = 加权证据 - 伪迹风险'],
  ['early recruitment and baseline deviation', '早期募集与基线偏离'],
  ['shorter recruitment latency', '募集潜伏期更短'],
  ['persistent rhythm and frequency migration', '持续节律与频率迁移'],
  ['directed graph outflow above baseline', '高于基线的有向图外流'],
  ['cross-seizure ranking consistency', '跨发作排序一致性'],
  ['recruitment head confidence', '募集头置信度'],
  ['bad-channel and artifact penalty', '坏道与伪迹惩罚'],
  ['Non-negative weights sum to 1', '非负权重之和为 1'],
  ['sample-wise percentile ranks prevent energy alone from dominating', '样本内百分位秩避免能量指标单独主导'],
  ['Top-10 output', 'Top-10 输出'],
  ['official channel IDs, ordered by S_c', '按 S_c 排序的官方通道 ID'],
  ['Conditional spatial mapping', '条件性空间映射'],
  ['coordinates + MRI/CT + quality control', '坐标 + MRI/CT + 质量控制'],
  ['contact -> region aggregation and 3D path', '接点 -> 脑区聚合与三维路径'],
  ['contact / ROI', '接点 / 脑区'],
  ['Not SOZ / EZ / surgical boundary', '不等同于 SOZ / EZ / 手术边界'],
  ['only important channels within current implant coverage', '仅表示当前植入覆盖范围内的重要通道'],
  ['Fast ranking uses one forward pass; attribution validates necessity and sufficiency offline.', '快速排序由一次前向完成；归因用于离线验证必要性与充分性。'],

  ['Streaming inference, cache reuse and explanation separation', '流式推理、缓存复用与解释分层'],
  ['formal fast path · CPU/GPU deployment · offline validation', '正式快速链路 · CPU/GPU 部署 · 离线验证'],
  ['A  FORMAL FAST INFERENCE PIPELINE', 'A  正式快速推理链路'],
  ['B  STREAMING CACHE AND HARDWARE LANES', 'B  流式缓存与硬件路径'],
  ['C  OFFLINE EXPLANATION AND QA', 'C  离线解释与质量核验'],
  ['Read + audit', '读取 + 审计'],
  ['shape · IDs · fs', '形状 · ID · 采样率'],
  ['Preprocess', '预处理'],
  ['filter · mask · scale', '滤波 · 掩码 · 标准化'],
  ['Window + cache', '滑窗 + 缓存'],
  ['overlap reuse', '重叠计算复用'],
  ['One forward', '一次前向'],
  ['state · onset · r_c,t', '状态 · onset · r_c,t'],
  ['single forward pass', '单次前向计算'],
  ['Post-process', '后处理'],
  ['calibration · hysteresis', '校准 · 滞回'],
  ['P50 / P95 tracked', '记录 P50 / P95'],
  ['Format', '结果格式化'],
  ['JSON / official fields', 'JSON / 官方字段'],
  ['deterministic stage', '确定性处理环节'],
  ['Only positive samples emit onset; all fields are checked by the submission validator.', '仅阳性样本输出 onset；所有字段通过提交校验。'],
  ['Sliding-window ring buffer', '滑窗环形缓存'],
  ['4 s context, 0.5 s step', '4 s 上下文，0.5 s 步长'],
  ['cached', '已缓存'],
  ['new 0.5 s', '新增 0.5 s'],
  ['Reusable features', '可复用特征'],
  ['filtered signal · STFT frames', '滤波信号 · STFT 帧'],
  ['local encoder state · graph edges', '局部编码状态 · 图边'],
  ['CPU: ONNX Runtime / OpenVINO / INT8', 'CPU：ONNX Runtime / OpenVINO / INT8'],
  ['GPU: TensorRT / FP16 or BF16 / dynamic batch', 'GPU：TensorRT / FP16 或 BF16 / 动态批处理'],
  ['Fast chain', '快速链路'],
  ['state + boundary + recruitment + graph outflow', '状态 + 边界 + 募集 + 图外流'],
  ['no reverse-mode explanation in the formal path', '正式链路不执行反向归因'],
  ['Deep explanation chain', '深度解释链路'],
  ['Integrated Gradients · SmoothGrad · occlusion · perturbation stability', 'Integrated Gradients · SmoothGrad · 遮挡 · 扰动稳定性'],
  ['offline validation and difficult-case review only', '仅用于离线验证与疑难片段复核'],
  ['QA branch', '质量核验支路'],
  ['Latency budget', '时延预算'],
  ['I/O · preprocess · forward · postprocess', 'I/O · 预处理 · 前向 · 后处理'],
  ['report cold-start and steady-state P50/P95', '报告冷启动与稳态 P50/P95'],
  ['Neural-network time and end-to-end system time are reported separately.', '分别报告神经网络耗时与端到端系统耗时。'],

  ['Model lightweight optimization and deployment acceptance gates', '模型轻量化优化与部署准入门槛'],
  ['distillation · quantization · cache reuse · deployment gates', '蒸馏 · 量化 · 缓存复用 · 部署准入'],
  ['A  TEACHER -> STUDENT DISTILLATION', 'A  教师 -> 学生蒸馏'],
  ['B  HARDWARE-AWARE COMPRESSION', 'B  面向硬件的压缩'],
  ['C  DEPLOYMENT GATES', 'C  部署准入门槛'],
  ['Teacher', '教师模型'],
  ['full QST-DPGNet', '完整 QST-DPGNet'],
  ['wide graph + long context', '宽动态图 + 长上下文'],
  ['soft logits + frame curves', '软 logits + 帧级曲线'],
  ['Student', '学生模型'],
  ['compact deployment model', '紧凑部署模型'],
  ['fewer graph layers and blocks', '更少图层与时序块'],
  ['rank-preserving outputs', '保持排序稳定的输出'],
  ['distill', '蒸馏'],
  ['Knowledge transfer targets', '知识迁移目标'],
  ['fragment probability · frame state · intermediate features', '片段概率 · 帧级状态 · 中间特征'],
  ['Top-10 ranking stability', 'Top-10 排序稳定性'],
  ['Structured pruning', '结构化剪枝'],
  ['conv channels · attention heads · graph width', '卷积通道 · 注意力头 · 图层宽度'],
  ['keep only hardware-effective sparsity', '仅保留硬件可实际加速的稀疏结构'],
  ['Quantization', '量化'],
  ['INT8 conv / linear layers on CPU', 'CPU 上量化卷积 / 线性层至 INT8'],
  ['keep calibration and onset postprocess in FP32', '校准与 onset 后处理保留 FP32'],
  ['Cache reuse', '缓存复用'],
  ['share filter, STFT and local features across windows', '跨窗口共享滤波、STFT 与局部特征'],
  ['new computation only for the 0.5 s increment', '仅计算新增 0.5 s 数据'],
  ['precision and latency are measured after export', '精度与时延以导出模型为准'],
  ['TensorRT', 'TensorRT'],
  ['GPU · FP16 · operator fusion', 'GPU · FP16 · 算子融合'],
  ['ONNX Runtime / OpenVINO', 'ONNX Runtime / OpenVINO'],
  ['CPU · INT8 · thread binding', 'CPU · INT8 · 线程绑定'],
  ['TorchScript', 'TorchScript'],
  ['research reproduction · fixed graph', '研究复现 · 固定推理图'],
  ['Acceptance gates', '准入门槛'],
  ['classification drop <= 0.5-1.0 pp', '分类性能下降 <= 0.5-1.0 个百分点'],
  ['increase <= 10%', '增幅 <= 10%'],
  ['ranking stability above threshold', '排序稳定性高于阈值'],
  ['end-to-end target hardware latency', '目标硬件端到端时延'],
  ['Validation gates cover probability, onset and ranking.', '准入同时约束概率、onset 与通道排序。']
];

map.push(
  ['The audit report fixes preprocessing, windowing and split rules before model selection.', '审计报告在模型选择前固定预处理、切窗与数据划分规则。'],
  ['earliest candidate satisfying future persistence', '满足后续持续性的最早候选点'],
  ['the first valid peak is selected, not the first p_t &gt; 0.5', '选择第一个满足约束的有效峰值，而非首次 p_t &gt; 0.5'],
  ['Hysteresis', '滞回机制'],
  ['trigger at tau_h  |  maintain at tau_l  |  tau_h &gt; tau_l', 'tau_h 触发  |  tau_l 保持  |  tau_h &gt; tau_l'],
  ['continuous positive duration D_min', '连续阳性时长 D_min'],
  ['A  TEACHER -&gt; STUDENT DISTILLATION', 'A  教师 -&gt; 学生蒸馏'],
  ['classification drop &lt;= 0.5-1.0 pp', '分类性能下降 &lt;= 0.5-1.0 个百分点'],
  ['increase &lt;= 10%', '增幅 &lt;= 10%'],
  ['early propagation', '早期传播'],
  ['late propagation', '晚期传播'],
  ['contact -&gt; region aggregation and 3D path', '接点 -&gt; 脑区聚合与三维路径']
);

map.sort((a, b) => b[0].length - a[0].length);

for (const name of figures) {
  let svg = fs.readFileSync(path.join(root, 'figures', `${name}.svg`), 'utf8');
  svg = svg.replaceAll('Arial,Helvetica,sans-serif', 'PingFang SC,Noto Sans CJK SC,Microsoft YaHei,Arial,Helvetica,sans-serif');
  const translateText = (text) => {
    let value = text;
    for (const [from, to] of map) value = value.replaceAll(from, to);
    return value;
  };
  svg = svg.replace(/>([^<>]*)</g, (_, text) => `>${translateText(text)}<`);
  fs.writeFileSync(path.join(root, 'figures', `${name}_zh.svg`), svg, 'utf8');
}
console.log('Generated Chinese SVG variants.');
